name: Count Interest Characters

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Check Long Enough
      run: |
        test $(wc -m src/interest.txt | cut -d " " -f 1) -ge 2500

    - name: Check Not Too Long
      run: |
        test $(wc -m src/interest.txt | cut -d " " -f 1) -le 5000
