name: Render Resume

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        sudo apt install -y pandoc

    - name: Build
      run: |
        mkdir build
        pandoc -o build/resume.pdf src/resume.md

    - name: Check Built
      run: |
        test -f build/resume.pdf
